import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Button from '@/components/Button'
import Footer from '@/components/Footer'
import TextBox from '@/components/TextBox'
import Link from '@/components/Link'



export default function Home() {
  return (
    <>
        <div className ={`${styles.bg}`}>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
      <header>

      </header>
     
      <main className={`${styles.main}`}>
          <div className={`${styles.generalcontainer}`}>
            <div className={`${styles.phone}`}>
            <Image src={'/images/Phone.png'} alt="instagram phone" width={250} height={500}/>
            </div>
          <div classNamestyles>
          <div className={`${styles.box1}`}>
          <Image className={`${styles.logo}`} src={'/images/instagram-logo.png'} alt="instagram logo" width={180} height={75} />
          <TextBox/>
          <Button/>
          <div className={`${styles.line}`}>
              <div className={`${styles.line1}`}>
                <p> ______________</p>
              </div>
          <p className ={`${styles.p}`}> OR </p>
            <div className={`${styles.line2}`}>
              <p> _______________</p>
            </div>
          </div>
            <div className={`${styles.facebook}`}>
            <Image className={`${styles.facebookicon}`} src={`/images/facebook-icon.png`} alt="facebook logo" width={25} height={25}/>
            <p className={`${styles.facebookp}`}> Log in with Facebook </p>
            </div>
            <p className={`${styles.p2}`}> Forgot password? </p>
          </div>
          <div className={`${styles.box2}`}>
            <p className={`${styles.text1}`}> Don't have account?</p>
            <p className={`${styles.text2}`}> Sign up</p>
          </div>
          <div className={`${styles.box3}`}>
            <p className={`${styles.text1}`}> Get the app </p>
            <Image className={`${styles.app}`} src={`/images/app.png`} alt="apple store" width={300} height={45}/>
          </div>
        </div>
      </div>
</main>

      <Link/>
      <Footer/>
      </div>
      </div>
    </>
  )
}
